# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_polydar <- function(x, dim, xyThresh, alpha, lmax, minTriangles) {
    .Call(`_polydar_rcpp_polydar`, x, dim, xyThresh, alpha, lmax, minTriangles)
}

